import { MigrationInterface, QueryRunner } from "typeorm";

export class InitPostgres1776663883603 implements MigrationInterface {
    name = 'InitPostgres1776663883603'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Enable UUID extension for UUID generation
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

        await queryRunner.query(`CREATE TABLE "email_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient_email" character varying(100) NOT NULL, "recipient_name" character varying(100), "subject" character varying(200) NOT NULL, "body" text NOT NULL, "template" character varying(50) NOT NULL, "status" character varying(50) NOT NULL, "error_message" text, "metadata" jsonb, "sent_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_edfd3f7225051fc07bdd63a22dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecbffcd25b85459ccf5e753e01" ON "email_log" ("recipient_email", "created_at") `);
        await queryRunner.query(`CREATE TABLE "country" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "iso3" character varying(3) NOT NULL, "iso2" character varying(2) NOT NULL, "phone_code" character varying(10), "currency" character varying(10), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8df5b1a0131e8e155381547aa5b" UNIQUE ("iso3"), CONSTRAINT "UQ_b49a3cfa4a8ab50b388f893cd4c" UNIQUE ("iso2"), CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(255), "permissions" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4a77d431a6b2ac981c342b13c94" UNIQUE ("name"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a77d431a6b2ac981c342b13c9" ON "user_roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "room" ("id" SERIAL NOT NULL, "restaurant_id" integer NOT NULL, "name" character varying(100) NOT NULL, "description" text, "capacity" integer NOT NULL, "price_per_night" numeric(10,2) NOT NULL, "original_price" numeric(10,2), "size" character varying(50), "bed_type" character varying(50), "discount" character varying(50), "image_url" character varying(255), "image_gallery" text, "available" boolean NOT NULL DEFAULT true, "featured" boolean NOT NULL DEFAULT false, "popular" boolean NOT NULL DEFAULT false, "family" boolean NOT NULL DEFAULT false, "luxury" boolean NOT NULL DEFAULT false, "romantic" boolean NOT NULL DEFAULT false, "accessible" boolean NOT NULL DEFAULT false, "pet_friendly" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_c6d46db005d623e691b2fbcba23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_booking" ("id" SERIAL NOT NULL, "booking_number" character varying(20) NOT NULL, "room_id" integer NOT NULL, "user_id" integer NOT NULL, "check_in_date" date NOT NULL, "check_out_date" date NOT NULL, "number_of_guests" integer NOT NULL, "total_price" numeric(10,2) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'Pending', "payment_id" integer, "special_requests" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d0427afc424572db29225055281" UNIQUE ("booking_number"), CONSTRAINT "PK_37af696e6aeb3fcb059778a96ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0636ea72b90d6196820447479" ON "room_booking" ("room_id", "check_in_date") `);
        await queryRunner.query(`CREATE TABLE "invoice" ("id" SERIAL NOT NULL, "payment_id" integer NOT NULL, "invoice_number" character varying(50) NOT NULL, "pdf_url" character varying(255), "issued_at" TIMESTAMP NOT NULL, "sent_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c7ec75a1a4068196ea74b920df9" UNIQUE ("invoice_number"), CONSTRAINT "PK_15d25c200d9bcd8a33f698daf18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" SERIAL NOT NULL, "payment_number" character varying(50) NOT NULL, "email" character varying(255) NOT NULL, "authorization_url" character varying(255), "user_id" integer NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'KES', "payment_method" character varying(50) NOT NULL, "gateway" character varying(50) NOT NULL, "payment_reference" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "transaction_id" character varying(255), "gateway_reference" character varying(255), "gateway_response" character varying(4000), "failure_reason" character varying(255), "refunded_amount" numeric(10,2) NOT NULL DEFAULT '0', "processed_at" TIMESTAMP DEFAULT now(), "failed_at" TIMESTAMP, "paid_at" TIMESTAMP, "channel" character varying(255), "metadata" character varying(2000), "delivery_initiated" boolean NOT NULL DEFAULT false, "delivery_reference" integer, "delivery_error" character varying(2000), "callback_url" character varying(1000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "order_id" integer, "reservation_id" integer, "room_booking_id" integer, CONSTRAINT "UQ_28f823091ff91a736d72a206e07" UNIQUE ("payment_number"), CONSTRAINT "UQ_54fc428ca06ce52fd478d8706d8" UNIQUE ("payment_reference"), CONSTRAINT "REL_fc0069dbffe962f7b1604c1410" UNIQUE ("reservation_id"), CONSTRAINT "REL_68cdd285bf17d1527f6a213c39" UNIQUE ("room_booking_id"), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reservation" ("id" SERIAL NOT NULL, "reservation_number" character varying(20) NOT NULL, "user_id" integer NOT NULL, "restaurant_id" integer NOT NULL, "table_id" integer, "reservation_type" character varying(20) NOT NULL, "reservation_date" date NOT NULL, "reservation_time" TIME NOT NULL, "guest_count" integer NOT NULL, "special_request" text, "status" character varying(20) NOT NULL DEFAULT 'Pending', "payment_id" integer, "deposit_amount" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d1e817e306498b6515b78ab2bcc" UNIQUE ("reservation_number"), CONSTRAINT "PK_48b1f9922368359ab88e8bfa525" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_84a0268487fde50cc3a50f3e8a" ON "reservation" ("restaurant_id", "reservation_date") `);
        await queryRunner.query(`CREATE TABLE "table" ("id" SERIAL NOT NULL, "restaurant_id" integer NOT NULL, "table_number" character varying(20) NOT NULL, "capacity" integer NOT NULL, "location" character varying(100), "status" character varying(20) NOT NULL DEFAULT 'Available', "minimum_charge" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28914b55c485fc2d7a101b1b2a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "street_address_1" character varying(255) NOT NULL, "street_address_2" character varying(255), "zip_code" character varying(20) NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "label" character varying(100), "is_default" boolean NOT NULL DEFAULT false, "city_id" integer NOT NULL, "delivery_instructions" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status" ("id" SERIAL NOT NULL, "order_id" integer NOT NULL, "status_catalog_id" integer NOT NULL, "notes" text, "updated_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ea75b2a26f83f3bc98b9c6aaf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status_catalog" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(255), "color" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e629db30e446da6cf12d443fc10" UNIQUE ("name"), CONSTRAINT "PK_3cd164e4ea4b993994152208a52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "image_url" character varying(255), "sort_order" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "restaurant_id" integer, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "restaurant_id" integer, "menu_item_id" integer, "order_id" integer, "rating" integer NOT NULL, "comment" text, "images" character varying, "verified" boolean NOT NULL DEFAULT true, "admin_response" text, "response_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6781107b20e9aed484c340e908" ON "review" ("menu_item_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7258583122a81366d02d06f7af" ON "review" ("restaurant_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "menu_item" ("id" SERIAL NOT NULL, "restaurant_id" integer NOT NULL, "category_id" integer NOT NULL, "name" character varying(200) NOT NULL, "description" text, "price" numeric(10,2) NOT NULL, "ingredients" text, "image_url" character varying(255), "available" boolean NOT NULL DEFAULT true, "is_featured" boolean NOT NULL DEFAULT false, "allergens" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_722c4de0accbbfafc77947a8556" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c92955bfc77b52366c99bd065b" ON "menu_item" ("restaurant_id", "category_id") `);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" SERIAL NOT NULL, "order_id" integer NOT NULL, "menu_item_id" integer NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, "comment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_tracking" ("id" SERIAL NOT NULL, "order_id" integer NOT NULL, "driver_id" integer NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "speed" numeric(5,2), "heading" numeric(5,2), "distance_to_destination" numeric(10,2), "eta_minutes" integer, "status" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_165d1402d6af7bb3aa56eecd0f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f701a8fb1c77001a8c9c9ac3c" ON "delivery_tracking" ("order_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "order_number" character varying(20) NOT NULL, "restaurant_id" integer NOT NULL, "user_id" integer NOT NULL, "driver_id" integer, "table_id" integer, "delivery_address_id" integer, "order_type" character varying(20) NOT NULL, "payment_id" integer, "status_id" integer NOT NULL, "total_price" numeric(10,2) NOT NULL, "discount" numeric(10,2) NOT NULL DEFAULT '0', "delivery_fee" numeric(10,2) NOT NULL DEFAULT '0', "tax_amount" numeric(10,2) NOT NULL DEFAULT '0', "final_price" numeric(10,2) NOT NULL, "comment" text, "estimated_delivery_time" TIMESTAMP, "actual_delivery_time" TIMESTAMP, "scheduled_time" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_75eba1c6b1a66b09f2a97e6927b" UNIQUE ("order_number"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_222cd7bf166a2d7a6aad9cdebe" ON "orders" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c884e321f927d5b86aac7c8f9e" ON "orders" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0379c1cb8cd158363b657fd849" ON "orders" ("restaurant_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "vehicle_info" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "vehicle_make" character varying(50) NOT NULL, "vehicle_model" character varying(50) NOT NULL, "vehicle_year" character varying(4) NOT NULL, "license_plate" character varying(20) NOT NULL, "license_number" character varying(50), "color" character varying(50), "vehicle_type" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f67df89a1a40c7d272f32a7bb0b" UNIQUE ("user_id"), CONSTRAINT "UQ_ef6652f2af642a4731dc58937c6" UNIQUE ("license_plate"), CONSTRAINT "REL_f67df89a1a40c7d272f32a7bb0" UNIQUE ("user_id"), CONSTRAINT "PK_098f6cf94c6ab295745f1d73ff2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shift" ("id" SERIAL NOT NULL, "staff_id" integer NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "shift_date" date NOT NULL, "status" character varying(50), "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53071a6485a1e9dc75ec3db54b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b41697313e0aad1c91fa14a9b9" ON "shift" ("staff_id", "shift_date") `);
        await queryRunner.query(`CREATE TABLE "restaurant_staff" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "restaurant_id" integer NOT NULL, "position" character varying(100) NOT NULL, "salary" numeric(10,2), "hire_date" date NOT NULL, "active" boolean NOT NULL DEFAULT true, "emergency_contact" character varying(100), "emergency_phone" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_973c53bdc06495c9daf779e23f3" UNIQUE ("user_id"), CONSTRAINT "REL_973c53bdc06495c9daf779e23f" UNIQUE ("user_id"), CONSTRAINT "PK_6b47b2ff71d81e5d3c18117b228" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_assignments" ("id" SERIAL NOT NULL, "restaurant_id" integer NOT NULL, "staff_id" integer NOT NULL, "role" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ab013446523a48ceb9b14144530" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "driver_assignments" ("id" SERIAL NOT NULL, "restaurant_id" integer NOT NULL, "driver_id" integer NOT NULL, "vehicleType" character varying, "licensePlate" character varying, "status" character varying NOT NULL DEFAULT 'active', "workingHours" jsonb, "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b72677caff7b7e9acad3d55b3ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "email" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "password" character varying(255) NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "profile_image" character varying(255), "active" boolean NOT NULL DEFAULT true, "status" character varying(30) NOT NULL DEFAULT 'pending_verification', "reset_token" character varying(100), "verification_token" character varying(100), "reset_token_expiry" TIMESTAMP, "role_id" integer NOT NULL, "is_online" boolean NOT NULL DEFAULT false, "is_available" boolean NOT NULL DEFAULT false, "current_latitude" numeric(10,7), "current_longitude" numeric(10,7), "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "total_deliveries" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2cecd1a3531c0b041e29ba46e" ON "users" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "restaurant" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, "description" text, "email" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "street_address" character varying(255) NOT NULL, "zip_code" character varying(20) NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "logo_url" character varying(255), "cover_image_url" character varying(255), "opening_time" TIME, "closing_time" TIME, "active" boolean NOT NULL DEFAULT true, "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "owner_id" integer NOT NULL, "city_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d055cac5f0f06d57b0a3b1fe574" UNIQUE ("email"), CONSTRAINT "PK_649e250d8b8165cb406d99aa30f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "city" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "state_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "state" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(10) NOT NULL, "country_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_549ffd046ebab1336c3a8030a12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transaction" ("id" SERIAL NOT NULL, "inventory_item_id" integer NOT NULL, "quantity_change" integer NOT NULL, "transaction_type" character varying(20) NOT NULL, "reference_id" character varying(100), "reason" character varying(255), "performed_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a81a89b9130bda3a5277cce53a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0eac8d9bcb0be44d349b122979" ON "stock_transaction" ("inventory_item_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "inventory_item" ("id" SERIAL NOT NULL, "restaurant_id" integer NOT NULL, "supplier_id" integer NOT NULL, "name" character varying(200) NOT NULL, "category" character varying(100) NOT NULL, "quantity" integer NOT NULL, "unit" character varying(50) NOT NULL, "unit_price" numeric(10,2) NOT NULL, "threshold" integer NOT NULL, "sku" character varying(50), "expiry_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94f5cbcb5f280f2f30bd4a9fd90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32c5687918533fbb6f0c12db6a" ON "inventory_item" ("restaurant_id", "category") `);
        await queryRunner.query(`CREATE TABLE "supplier" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, "contact_name" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(100) NOT NULL, "address" character varying(255) NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2bc0d2cab6276144d2ff98a2828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "token" character varying(500) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "ip_address" character varying(50), "user_agent" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "user_behavior" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "session_date" date NOT NULL, "session_id" character varying(50) NOT NULL, "page_views" integer NOT NULL, "menu_views" integer NOT NULL, "restaurant_views" integer NOT NULL, "items_added_to_cart" integer NOT NULL, "checkout_attempts" integer NOT NULL, "completed_orders" integer NOT NULL, "reservation_attempts" integer NOT NULL, "completed_reservations" integer NOT NULL, "room_booking_attempts" integer NOT NULL, "completed_room_bookings" integer NOT NULL, "session_duration_seconds" integer NOT NULL, "device_type" character varying(50), "browser" character varying(50), "platform" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7cd6d00de0e036b185f6a23eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc5c5ce5901245af0baff0d20b" ON "user_behavior" ("session_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6ffc42dd1f62d01a1bf609627" ON "user_behavior" ("user_id", "session_date") `);
        await queryRunner.query(`CREATE TABLE "business_metrics" ("id" SERIAL NOT NULL, "restaurant_id" integer, "date" date NOT NULL, "total_revenue" numeric(12,2) NOT NULL, "online_revenue" numeric(12,2) NOT NULL, "dine_in_revenue" numeric(12,2) NOT NULL, "delivery_revenue" numeric(12,2) NOT NULL, "total_orders" integer NOT NULL, "online_orders" integer NOT NULL, "dine_in_orders" integer NOT NULL, "delivery_orders" integer NOT NULL, "average_order_value" numeric(8,2) NOT NULL, "new_customers" integer NOT NULL, "returning_customers" integer NOT NULL, "customer_satisfaction_score" numeric(5,2) NOT NULL, "total_reservations" integer NOT NULL, "confirmed_reservations" integer NOT NULL, "cancelled_reservations" integer NOT NULL, "reservation_utilization_rate" numeric(5,2) NOT NULL, "total_room_bookings" integer NOT NULL, "occupied_rooms" integer NOT NULL, "occupancy_rate" numeric(5,2) NOT NULL, "top_selling_items" text, "low_performing_items" text, "total_preparation_time_minutes" integer NOT NULL, "average_preparation_time_minutes" integer NOT NULL, "total_delivery_time_minutes" integer NOT NULL, "average_delivery_time_minutes" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0e0b099eef5add99fc9467bc5fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b1205412935e9808d67db525f" ON "business_metrics" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_bce0c6633d28494d9a8bc56cd0" ON "business_metrics" ("restaurant_id", "date") `);
        await queryRunner.query(`CREATE TABLE "activity_log" ("id" SERIAL NOT NULL, "user_id" integer, "action" character varying(100) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" character varying(100) NOT NULL, "old_values" text, "new_values" text, "ip_address" character varying(50), "user_agent" character varying(255), "description" text, "session_id" character varying(50), "timestamp" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_067d761e2956b77b14e534fd6f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13f3cf247b11fa7fa38be36f01" ON "activity_log" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_959edb8257ad43d7cb2f8d095e" ON "activity_log" ("action", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_4302f461733b6ec81cd7d023f8" ON "activity_log" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_41b703a3dce9703a30e53ae454" ON "activity_log" ("user_id", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "otps" ("otp_id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "otp_code" character varying(10) NOT NULL, "otp_type" character varying(30) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "expires_at" TIMESTAMP NOT NULL, "verified_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d73db5899adf59583abd31e2309" PRIMARY KEY ("otp_id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "type" character varying(100) NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "priority" character varying(20) NOT NULL DEFAULT 'medium', "metadata" character varying(255), "channel" character varying(50) NOT NULL DEFAULT 'in_app', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "is_sent" boolean NOT NULL DEFAULT false, "sent_at" TIMESTAMP, "scheduled_for" TIMESTAMP, "expires_at" TIMESTAMP, "action_url" character varying(255), "action_label" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ce8924c20fe5e65d1bf282f51" ON "notification" ("is_read", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_12a9a4259cea86d02b12fe93d6" ON "notification" ("type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_73bfce92922b5fdb3c378fc8b9" ON "notification" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "room" ADD CONSTRAINT "FK_e12f4703203a522f06b210d11af" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_booking" ADD CONSTRAINT "FK_fa30cbd7fa3588d5f8699503779" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_booking" ADD CONSTRAINT "FK_84de6b7898532f74e4e8c32066a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_b63cfba23ecc43531b5c571ffa3" FOREIGN KEY ("payment_id") REFERENCES "payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_f5221735ace059250daac9d9803" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_c66c60a17b56ec882fcd8ec770b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_fc0069dbffe962f7b1604c14104" FOREIGN KEY ("reservation_id") REFERENCES "reservation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_68cdd285bf17d1527f6a213c392" FOREIGN KEY ("room_booking_id") REFERENCES "room_booking"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_e219b0a4ff01b85072bfadf3fd7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_b8e66a59e3500c7a85cde4fb020" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_d3321fc44e70fd7e803491513d6" FOREIGN KEY ("table_id") REFERENCES "table"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "table" ADD CONSTRAINT "FK_1e79a861b6be1078a6b79e48ff9" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_35cd6c3fafec0bb5d072e24ea20" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_714a4ca3cfd66a718b5f7c3fee5" FOREIGN KEY ("city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status" ADD CONSTRAINT "FK_94eff27e795c6c02bdd07abd0ae" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status" ADD CONSTRAINT "FK_fc531e3259b71a7d8da5296a721" FOREIGN KEY ("status_catalog_id") REFERENCES "status_catalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_48be827a112f05347b53cbc330b" FOREIGN KEY ("restaurant_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_81446f2ee100305f42645d4d6c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_9e0a456057cd16f910bfad306ad" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_6b3c3b6826a71efc35fcf8d02d6" FOREIGN KEY ("menu_item_id") REFERENCES "menu_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD CONSTRAINT "FK_a3c3188fed5e5b458ea15047319" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_item" ADD CONSTRAINT "FK_0d7401f822dda4303ecdeea2ca1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_e9674a6053adbaa1057848cddfa" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_2dcc6c8c2d412597a9c8be73235" FOREIGN KEY ("menu_item_id") REFERENCES "menu_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_tracking" ADD CONSTRAINT "FK_9baaa588693ae1f7335b63fa4ac" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_tracking" ADD CONSTRAINT "FK_5ad8bf25a103cced651aef52c51" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_85fdda5fcce2f397ef8f117a2c6" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_222cd7bf166a2d7a6aad9cdebee" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_3d36410e89a795172fa6e0dd968" FOREIGN KEY ("table_id") REFERENCES "table"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_822c5ebe47e43ebe715f68968c4" FOREIGN KEY ("delivery_address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_03a801095cb90cf148e474cfcb7" FOREIGN KEY ("status_id") REFERENCES "status_catalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_info" ADD CONSTRAINT "FK_f67df89a1a40c7d272f32a7bb0b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift" ADD CONSTRAINT "FK_d030acf2e7099f931d515237ecb" FOREIGN KEY ("staff_id") REFERENCES "restaurant_staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_staff" ADD CONSTRAINT "FK_973c53bdc06495c9daf779e23f3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant_staff" ADD CONSTRAINT "FK_14050e881d650b217075f1110c4" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" ADD CONSTRAINT "FK_6ac397c566a0f56bd6fe2b54262" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" ADD CONSTRAINT "FK_6ff0f6a29afcb34aa82e9963298" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_assignments" ADD CONSTRAINT "FK_444146448fe885ff036ecb47e46" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_assignments" ADD CONSTRAINT "FK_3b70749e81638d9f7e532c8b9a2" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "user_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_fe7a22ecf454b7168b5a37fbdce" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_6f2fe84da283ef2126d64bed513" FOREIGN KEY ("city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "FK_37ecd8addf395545dcb0242a593" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "state" ADD CONSTRAINT "FK_dd19065b0813dbffd8170ea6753" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transaction" ADD CONSTRAINT "FK_7ce6b58c7b0e3a43234ef0b0ed2" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_18dd0db74004e8690071cb13fd8" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_abb65d61d4c77ad7388c51bdb83" FOREIGN KEY ("supplier_id") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_behavior" ADD CONSTRAINT "FK_f906368b51143310b721aa4c833" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_log" ADD CONSTRAINT "FK_81615294532ca4b6c70abd1b2e6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "activity_log" DROP CONSTRAINT "FK_81615294532ca4b6c70abd1b2e6"`);
        await queryRunner.query(`ALTER TABLE "user_behavior" DROP CONSTRAINT "FK_f906368b51143310b721aa4c833"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_abb65d61d4c77ad7388c51bdb83"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_18dd0db74004e8690071cb13fd8"`);
        await queryRunner.query(`ALTER TABLE "stock_transaction" DROP CONSTRAINT "FK_7ce6b58c7b0e3a43234ef0b0ed2"`);
        await queryRunner.query(`ALTER TABLE "state" DROP CONSTRAINT "FK_dd19065b0813dbffd8170ea6753"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "FK_37ecd8addf395545dcb0242a593"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_6f2fe84da283ef2126d64bed513"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_fe7a22ecf454b7168b5a37fbdce"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "driver_assignments" DROP CONSTRAINT "FK_3b70749e81638d9f7e532c8b9a2"`);
        await queryRunner.query(`ALTER TABLE "driver_assignments" DROP CONSTRAINT "FK_444146448fe885ff036ecb47e46"`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" DROP CONSTRAINT "FK_6ff0f6a29afcb34aa82e9963298"`);
        await queryRunner.query(`ALTER TABLE "staff_assignments" DROP CONSTRAINT "FK_6ac397c566a0f56bd6fe2b54262"`);
        await queryRunner.query(`ALTER TABLE "restaurant_staff" DROP CONSTRAINT "FK_14050e881d650b217075f1110c4"`);
        await queryRunner.query(`ALTER TABLE "restaurant_staff" DROP CONSTRAINT "FK_973c53bdc06495c9daf779e23f3"`);
        await queryRunner.query(`ALTER TABLE "shift" DROP CONSTRAINT "FK_d030acf2e7099f931d515237ecb"`);
        await queryRunner.query(`ALTER TABLE "vehicle_info" DROP CONSTRAINT "FK_f67df89a1a40c7d272f32a7bb0b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_03a801095cb90cf148e474cfcb7"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_822c5ebe47e43ebe715f68968c4"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_3d36410e89a795172fa6e0dd968"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_222cd7bf166a2d7a6aad9cdebee"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_85fdda5fcce2f397ef8f117a2c6"`);
        await queryRunner.query(`ALTER TABLE "delivery_tracking" DROP CONSTRAINT "FK_5ad8bf25a103cced651aef52c51"`);
        await queryRunner.query(`ALTER TABLE "delivery_tracking" DROP CONSTRAINT "FK_9baaa588693ae1f7335b63fa4ac"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_2dcc6c8c2d412597a9c8be73235"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_e9674a6053adbaa1057848cddfa"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP CONSTRAINT "FK_0d7401f822dda4303ecdeea2ca1"`);
        await queryRunner.query(`ALTER TABLE "menu_item" DROP CONSTRAINT "FK_a3c3188fed5e5b458ea15047319"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_6b3c3b6826a71efc35fcf8d02d6"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_9e0a456057cd16f910bfad306ad"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_81446f2ee100305f42645d4d6c2"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_48be827a112f05347b53cbc330b"`);
        await queryRunner.query(`ALTER TABLE "order_status" DROP CONSTRAINT "FK_fc531e3259b71a7d8da5296a721"`);
        await queryRunner.query(`ALTER TABLE "order_status" DROP CONSTRAINT "FK_94eff27e795c6c02bdd07abd0ae"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_714a4ca3cfd66a718b5f7c3fee5"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_35cd6c3fafec0bb5d072e24ea20"`);
        await queryRunner.query(`ALTER TABLE "table" DROP CONSTRAINT "FK_1e79a861b6be1078a6b79e48ff9"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_d3321fc44e70fd7e803491513d6"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_b8e66a59e3500c7a85cde4fb020"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_e219b0a4ff01b85072bfadf3fd7"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_68cdd285bf17d1527f6a213c392"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_fc0069dbffe962f7b1604c14104"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_c66c60a17b56ec882fcd8ec770b"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_f5221735ace059250daac9d9803"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_b63cfba23ecc43531b5c571ffa3"`);
        await queryRunner.query(`ALTER TABLE "room_booking" DROP CONSTRAINT "FK_84de6b7898532f74e4e8c32066a"`);
        await queryRunner.query(`ALTER TABLE "room_booking" DROP CONSTRAINT "FK_fa30cbd7fa3588d5f8699503779"`);
        await queryRunner.query(`ALTER TABLE "room" DROP CONSTRAINT "FK_e12f4703203a522f06b210d11af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73bfce92922b5fdb3c378fc8b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12a9a4259cea86d02b12fe93d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce8924c20fe5e65d1bf282f51"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41b703a3dce9703a30e53ae454"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4302f461733b6ec81cd7d023f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_959edb8257ad43d7cb2f8d095e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13f3cf247b11fa7fa38be36f01"`);
        await queryRunner.query(`DROP TABLE "activity_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bce0c6633d28494d9a8bc56cd0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b1205412935e9808d67db525f"`);
        await queryRunner.query(`DROP TABLE "business_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6ffc42dd1f62d01a1bf609627"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc5c5ce5901245af0baff0d20b"`);
        await queryRunner.query(`DROP TABLE "user_behavior"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "supplier"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32c5687918533fbb6f0c12db6a"`);
        await queryRunner.query(`DROP TABLE "inventory_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0eac8d9bcb0be44d349b122979"`);
        await queryRunner.query(`DROP TABLE "stock_transaction"`);
        await queryRunner.query(`DROP TABLE "state"`);
        await queryRunner.query(`DROP TABLE "city"`);
        await queryRunner.query(`DROP TABLE "restaurant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2cecd1a3531c0b041e29ba46e"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "driver_assignments"`);
        await queryRunner.query(`DROP TABLE "staff_assignments"`);
        await queryRunner.query(`DROP TABLE "restaurant_staff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b41697313e0aad1c91fa14a9b9"`);
        await queryRunner.query(`DROP TABLE "shift"`);
        await queryRunner.query(`DROP TABLE "vehicle_info"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0379c1cb8cd158363b657fd849"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c884e321f927d5b86aac7c8f9e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_222cd7bf166a2d7a6aad9cdebe"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f701a8fb1c77001a8c9c9ac3c"`);
        await queryRunner.query(`DROP TABLE "delivery_tracking"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c92955bfc77b52366c99bd065b"`);
        await queryRunner.query(`DROP TABLE "menu_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7258583122a81366d02d06f7af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6781107b20e9aed484c340e908"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "status_catalog"`);
        await queryRunner.query(`DROP TABLE "order_status"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "table"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84a0268487fde50cc3a50f3e8a"`);
        await queryRunner.query(`DROP TABLE "reservation"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0636ea72b90d6196820447479"`);
        await queryRunner.query(`DROP TABLE "room_booking"`);
        await queryRunner.query(`DROP TABLE "room"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a77d431a6b2ac981c342b13c9"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "country"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecbffcd25b85459ccf5e753e01"`);
        await queryRunner.query(`DROP TABLE "email_log"`);
    }

}
